### ISSUE TITLE
GDAX price feed is unreliable

### ISSUE THREAD

**Issue by ghost** [makerdao/setzer#14]
GDAX ticket endpoint is unreliable as it returns outdated prices sometimes. Too see it, just run:
```
while true; do date; setzer price gdax; done
```

and wait a couple of minutes looking closely at the values. You will definitely find something like that among them:
```
Mon Jan  1 13:55:09 CET 2018
{"trade_id":23873529,"price":"750.60000000","size":"0.01418975","bid":"750.61","ask":"750.62","volume":"91578.03161872","time":"2018-01-01T12:54:56.751000Z"}
750.60000000
Mon Jan  1 13:55:09 CET 2018
{"trade_id":23873529,"price":"750.60000000","size":"0.01418975","bid":"750.61","ask":"750.62","volume":"91578.03161872","time":"2018-01-01T12:54:56.751000Z"}
750.60000000
Mon Jan  1 13:55:10 CET 2018
{"trade_id":23845797,"price":"727.60000000","size":"0.60884259","bid":"727.6","ask":"727.61","volume":"91578.03161872","time":"2018-01-01T02:34:46.419000Z"}
727.60000000
Mon Jan  1 13:55:10 CET 2018
{"trade_id":23873529,"price":"750.60000000","size":"0.01418975","bid":"750.61","ask":"750.62","volume":"91578.03161872","time":"2018-01-01T12:54:56.751000Z"}
750.60000000
Mon Jan  1 13:55:11 CET 2018
{"trade_id":23873533,"price":"750.60000000","size":"7.41116863","bid":"750.6","ask":"750.61","volume":"91578.03161872","time":"2018-01-01T12:55:11.242000Z"}
750.60000000
Mon Jan  1 13:55:11 CET 2018
{"trade_id":23873534,"price":"750.61000000","size":"0.00132826","bid":"750.5","ask":"750.51","volume":"91578.03161872","time":"2018-01-01T12:55:11.958000Z"}
750.61000000
```

See the `727.60000000` outlier, it is a price from 10 hours ago!!!!

**Comment by tomedwardsmith** [comment]
Hi @reverendus - this is an old one - can we close it, or is it still relevant?

**Comment by ghost** [comment]
No idea to be honest. I reported that I spotted an exchange API returning stale prices, which is a bit worrying as this data is used in order to create the price feed. Having said we use a median so there is a chance that an API glitch like that will just go unnoticed. Also bear in mind that I have noticed that one year ago, so maybe these glitches do not happen anymore due to some fix applied by GDAX/Coinbase.

My answer is really inconclusive, I know. Up to you to decide guys.
