### ISSUE TITLE
`setzer price ls` returns error

### ISSUE THREAD

**Issue by NiklasKunkel** [makerdao/setzer#2]
```
nkunkel@Oracle:/usr/local/libexec/setzer$ setzer price ls
parse error: type 'object' has no elements to extract (arg 2)
```

Things like `setzer price kraken` work, it's just the `ls` that fails.

**Comment by nanexcool** [comment]
If one lookup fails, the whole script fails... will fix, thanks!

**Comment by nanexcool** [comment]
I think this is fixed. Could handle error more gracefully though
